=  Machine Write-Up
Colosion
:toc:
:toclevels: 3

== Table of Contents
- <<overview,Scope>>
- <<enumeration,Enumeration>>
- <<ad-enum,AD Enumeration>>
- <<ad-access,Lateral movement>>
- <<privesc,Privilege Escalation>>
- <<notes,Final Notes>>

[[overview]]
== Scope
*Objective*: You're a penetration tester on the Hack Smarter Red Team. Your mission is to infiltrate and seize control of the client's entire Active Directory environment. This isn't just a test; it's a full-scale assault to expose and exploit every vulnerability.

*Initial Access*: For this engagement, you've been granted direct network access to the client's network. The door is open, but you're starting with zero credentials. From here, every move counts.

*Execution*: Your objective is simple but demanding: enumerate, exploit, and own. Your ultimate goal is not just to get in, but to achieve a full compromise, elevating your privileges until you hold the keys to the entire domain.





[[enumeration]]
== Enumeration

[sourse]
----
nmap --top-ports 1000 -sC -sV 10.1.99.111 
----

Added to /etc/hosts 

hack.smarter DC01.hack.smarter

Nmap output

[sourse]
----
PORT     STATE SERVICE       VERSION
53/tcp   open  domain        Simple DNS Plus
88/tcp   open  kerberos-sec  Microsoft Windows Kerberos (server time: 2025-11-15 20:01:38Z)
135/tcp  open  msrpc         Microsoft Windows RPC
139/tcp  open  netbios-ssn   Microsoft Windows netbios-ssn
389/tcp  open  ldap          Microsoft Windows Active Directory LDAP (Domain: hack.smarter0., Site: Default-First-Site-Name)
| ssl-date: 
|_  ERROR: Unable to obtain data from the target
445/tcp  open  microsoft-ds?
464/tcp  open  kpasswd5?
593/tcp  open  ncacn_http    Microsoft Windows RPC over HTTP 1.0
636/tcp  open  tcpwrapped
| ssl-date: 
|_  ERROR: Unable to obtain data from the target
3268/tcp open  ldap          Microsoft Windows Active Directory LDAP (Domain: hack.smarter0., Site: Default-First-Site-Name)
| ssl-date: 
|_  ERROR: Unable to obtain data from the target
3269/tcp open  tcpwrapped
| ssl-date: 
|_  ERROR: Unable to obtain data from the target
3389/tcp open  ms-wbt-server Microsoft Terminal Services
|_ssl-date: 2025-11-15T20:01:56+00:00; -1s from scanner time.
| ssl-cert: Subject: commonName=DC01.hack.smarter
| Not valid before: 2025-09-05T03:46:00
|_Not valid after:  2026-03-07T03:46:00
| rdp-ntlm-info: 
|   Target_Name: HACK
|   NetBIOS_Domain_Name: HACK
|   NetBIOS_Computer_Name: DC01
|   DNS_Domain_Name: hack.smarter
|   DNS_Computer_Name: DC01.hack.smarter
|   DNS_Tree_Name: hack.smarter
|   Product_Version: 10.0.20348
|_  System_Time: 2025-11-15T20:01:47+00:00
5985/tcp open  http          Microsoft HTTPAPI httpd 2.0 (SSDP/UPnP)
|_http-title: Not Found
|_http-server-header: Microsoft-HTTPAPI/2.0
Service Info: Host: DC01; OS: Windows; CPE: cpe:/o:microsoft:windows

Host script results:
| nbstat: 
|_  ERROR: Name query failed: TIMEOUT
| smb2-time: 
|   date: 2025-11-15T20:01:50
|_  start_date: N/A
|_clock-skew: mean: -1s, deviation: 0s, median: -1s
| smb-os-discovery: 
|_  ERROR: Could not negotiate a connection:SMB: Failed to receive bytes: ERROR
| smb-security-mode: 
|_  ERROR: Could not negotiate a connection:SMB: Failed to receive bytes: ERROR
| smb2-security-mode: 
|   3:1:1: 
|_    Message signing enabled and required
Final times for host: srtt: 145042 rttvar: 3647  to: 159630
----



[sourse]
----
kali ~/hack_smarter/machines/ShareThePain $ nxc smb hack.smarter -u '' -p '' --shares
SMB         10.1.99.111     445    DC01             [*] Windows Server 2022 Build 20348 x64 (name:DC01) (domain:hack.smarter) (signing:True) (SMBv1:False)
SMB         10.1.99.111     445    DC01             [+] hack.smarter\: 
SMB         10.1.99.111     445    DC01             [*] Enumerated shares
SMB         10.1.99.111     445    DC01             Share           Permissions     Remark
SMB         10.1.99.111     445    DC01             -----           -----------     ------
SMB         10.1.99.111     445    DC01             ADMIN$                          Remote Admin
SMB         10.1.99.111     445    DC01             C$                              Default share
SMB         10.1.99.111     445    DC01             IPC$                            Remote IPC
SMB         10.1.99.111     445    DC01             NETLOGON                        Logon server share 
SMB         10.1.99.111     445    DC01             Share           READ,WRITE      
SMB         10.1.99.111     445    DC01             SYSVOL                          Logon server share 
----

Write and Read perms in share `Share`

[sourse]
----
kali ~/hack_smarter/machines/ShareThePain $ smbclient //hack.smarter/Share
Password for [WORKGROUP\kali]:
Try "help" to get a list of possible commands.
smb: \> ls
  .                                   D        0  Sat Nov 15 23:07:22 2025
  ..                                DHS        0  Sat Sep  6 06:46:21 2025
pu
                31292671 blocks of size 4096. 27391228 blocks available
smb: \> put smart.txt
putting file smart.txt as \smart.txt (0,0 kB/s) (average 0,0 kB/s)
smb: \> ls
  .                                   D        0  Sat Nov 15 23:31:26 2025
  ..                                DHS        0  Sat Sep  6 06:46:21 2025
  smart.txt                           A        0  Sat Nov 15 23:31:26 2025

                31292671 blocks of size 4096. 27391228 blocks available
----




[[ad-enum]]
== AD Enumeration



[[ad-access]]
== Lateral movement



[[privesc]]
== Privilege Escalation


[[notes]]
== Final Notes
